image: daewok/lisp-devel
# We don't need a working quicklisp anymore,
# Next's Makefile handles it, so we could use another image.

# We can try to build this image locally with gitlab-runner
# https://docs.gitlab.com/runner/install/linux-manually.html
# Command:
# gitlab-runner exec docker build

stages:
  - build

build-core:
  stage: build
  script:
    - make next
  artifacts:
    paths:
      - next

build-gtk-webkit:
  stage: build
  script:
    - apt update
    - apt install -qy libwebkit2gtk-4.0-dev
    - make gtk-webkit
  artifacts:
    # binary for Debian Jessie. The user still needs to install libwebkit2gtk-4.0-dev.
    # see shinmera/deploy.
    paths:
      - next
      - ports/gtk-webkit/next-gtk-webkit
